#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PhotoSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  button,         sensorTouch)
#pragma config(Sensor, dgtl4,  sonarLeftIn,    sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  sonarRightIn,   sensorSONAR_cm)
#pragma config(Sensor, dgtl11, LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motorL,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          motorR,        tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool button_pushed;

void monitorInput() //monitors which button is being pushed
{
	if(SensorValue(button) && !button_pushed)
	{
		button_pushed = true;
	}
}

void signal (){
	int i = 0;
	while(i < 10){
		SensorValue[LEDRed] = 1;
		wait1Msec(100);
		SensorValue[LEDRed] = 0;
		wait1Msec(100);
		i = i + 1;
	}
	return;
}

task main(){
	button_pushed = false;
	resetMotorEncoder(motorR);

	enum T_state {															//Declare states
		STOP,
		SEARCH,
		CLOSE_IN
	};

	T_state state = STOP;
	while (true){

		monitorInput();

		switch (state){
		case STOP:
			motor[motorL] = 0;
			motor[motorR] = 0;
			if (button_pushed) {
				state = SEARCH;
			}
			break;
		case SEARCH:
			if((SensorValue(PhotoSensor))< 600){
				motor[motorL] = 50;
				motor[motorR] = -50;
			}
			if((SensorValue(PhotoSensor))> 600){
				motor[motorL] = -10;
				motor[motorR] = 10;
				wait1Msec(500);
				motor[motorL] = 50;
				motor[motorR] = 50;
				wait1Msec(300);
				motor[motorL] = 0;
				motor[motorR] = 0;
				button_pushed = false;

				signal();
				state = STOP;
			}
			break;
		case CLOSE_IN:
			while((SensorValue(PhotoSensor))< 2000){
				motor[motorL] = -30;
				motor[motorR] = 30;
				wait1Msec(1500);
				motor[motorL] = 30;
				motor[motorR] = -30;
				wait1Msec(1500);
			}
			state = STOP;
			break;
			//default:
		}
	}
}
