#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PhotoSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  button,         sensorTouch)
#pragma config(Sensor, dgtl4,  sonarLeftIn,    sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  sonarRightIn,   sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  sonarMiddleIn,  sensorSONAR_cm)
#pragma config(Sensor, dgtl11, LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motorL,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          motorR,        tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void signal_tooClose() {																		//too close, short blinks
	while((SensorValue[sonarMiddleIn] > 0) && (SensorValue[sonarMiddleIn] < 6)){
		SensorValue[LEDRed] = 1;
		wait1Msec(90);
		SensorValue[LEDRed] = 0;
		wait1Msec(90);
	}
}

void signal_tooFar() {																	//too far, long blinks
	while(SensorValue[sonarMiddleIn] > 14){
		SensorValue[LEDRed] = 1;
		wait1Msec(700);
		SensorValue[LEDRed] = 0;
		wait1Msec(700);
	}
}

void signal_ballDropReady() {														//just right, LEDGreen stay on
	while((SensorValue[sonarMiddleIn] > 6) && (SensorValue[sonarMiddleIn] < 13)){
		SensorValue[LEDGreen] = 1;
	}
	SensorValue[LEDGreen] = 0;
}

void signal_targetDirection(){
	int i = 0;
	while(i < 10){
		SensorValue[LEDRed] = 1;
		wait1Msec(100);
		SensorValue[LEDRed] = 0;
		wait1Msec(100);
		i = i + 1;
	}
}

task main(){

	while(true){
		SensorValue[LEDGreen] = 0;
		if ((SensorValue[sonarMiddleIn] > 6) && (SensorValue[sonarMiddleIn] < 13)){
			signal_ballDropReady();
		}
		else if (SensorValue[sonarMiddleIn] > 14){
			signal_tooFar();
		}
		else if ((SensorValue[sonarMiddleIn] > 0) && (SensorValue[sonarMiddleIn] < 6)){
			signal_tooClose();
		}
		else{
			SensorValue[LEDRed] = 0;
		}
	}
}
