#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PhotoSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  button,         sensorTouch)
#pragma config(Sensor, dgtl4,  sonarLeftIn,    sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  sonarRightIn,   sensorSONAR_cm)
#pragma config(Sensor, dgtl11, LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motorL,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          motorR,        tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool leftTouched = false;

task main()
{
	if(leftTouched){
		leftTouched = false;
		motorStop();
		motor[motorL] = -60;
		motor[motorR] = -50;
		wait1Msec(2000);
	}
	if(rightTouched){
		rightTouched = false;
		motorStop();
		motor[motorL] = -50;
		motor[motorR] = -60;
		wait1Msec(2000);
	}


}
